services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false
      #bind:
      #   $projectDir: '%kernel.project_dir%'
      #   $db: '@database_connection'
      #   $stringParser: '@Codefog\HasteBundle\StringParser'
      #   $insertTagParser: '@contao.insert_tag.parser'
      #   $formManagerFactory: '@?Terminal42\MultipageFormsBundle\FormManagerFactoryInterface'

   Cgoit\MegaMenuBundle\:
      resource: ../src/*
