name: CI

on:
    pull_request: ~
    push: ~

permissions: read-all

jobs:
    ecs:
        name: build-tools
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2 # Run with the lowest supported to avoid incompatible fixes
                    extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the dependencies
                run: |
                    composer install --no-interaction --no-progress

            -   name: Run all build-tools to validate code
                run: composer run build-tools

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.2, 8.3 ]
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the dependencies
                run: composer install --no-interaction --no-progress

            -   name: Run the unit tests
                run: vendor/bin/phpunit --colors=always
